export const tagLibrary = {
  face: [
    "smug doyagao (自鸣得意)",
    "closed mouth (闭嘴)",
    "fang (虎牙)",
    "crazy angry smile，clenched_teeth (狂气龇牙/坏笑)",
    "sanpaku (三白眼)",
    "ringed eyes (圈圈眼)",
    "orgasm (高潮)",
    "sigh (叹息)",
    "heart-shaped pupils (爱心瞳)",
    "frown (皱眉)",
    "closed eyes (闭眼)",
    "sideways glance (斜视)",
    "clear face,expressionless (面无表情)",
    "bright pupils (发亮瞳孔)",
    "tsurime (吊眼角)",
    "naughty_face (下流的表情)",
    "Open mouth indicating flustered (慌乱嘴型(也是艾草的嘴型))",
    "heterochromia golden green (异色瞳)",
    "horns (犄角)",
    "horn (角)",
    "short eyebrows (短眉)",
    "beautiful golden eyes (金色的瞳孔)",
    "constricted pupils (收缩的瞳孔)",
    "one eye closed (闭单眼)",
    "wince (皱眉蹙眼)",
    "fucked silly (干到傻)",
    "looking down (往下看)",
    "licking (舔)",
    "open  mouth (张嘴)",
    "squinting (瞇眼)",
    "Glazed pupils, (琉璃瞳孔)",
    "bandage over one eye (绷带遮单眼)",
    "sleepy (想睡的)",
    "antlers (鹿角)",
    "horizontal pupils (水平瞳孔)",
    "tareme (下垂眼)",
    "beautiful_face (精致脸庞)",
    "gloom (expression) depressed (忧郁)",
    "glowing eyes (发光眼睛)",
    "eyelashes (眼睫毛)",
    "aquagradient eyes (水汪汪的眼睛)",
    "shaded face (阴暗脸)",
    "gradient eyes (渐变眼)",
    "half-closed eyes (半开眼)",
    "smug (洋洋得意)",
    "surprised (惊讶)",
    "scared (害怕)",
    "lipstick (口红)",
    "raised eyebrow (挑眉)",
    "uneven eyes (不对称眼)",
    "slit pupils (猫眼（竖瞳）)",
    "grin (露齿笑)",
    "torogao (恍惚放荡)",
    "sharp teeth (鲨鱼牙)",
    "ahegao (阿嘿颜)",
    "nervous (紧张)",
    "rolling eyes (翻白眼)",
    "drooling (流口水)",
    "empty eyes (失神眼)",
    "open mouth (开口)",
    "heart-shaped_pupils (爱心瞳孔)",
    "troll face (幸灾乐祸)",
    "heterochromia grey red (异色瞳)",
    "looking back (回头看)",
    "crying with eyes open (张眼哭)",
    "crazy eyes (疯狂眼睛)",
    "parted lips (开嘴)",
    "wide-eyed (睁大眼睛)",
    "heavy breathing (呼吸急促)",
    "no pupils (没有瞳孔)",
    "light smile (微笑)",
    "Cyan eyes (青色眼瞳)",
    "expressionless (无表情)",
    "hair over one eye one eye covered (单遮眼)",
    "heterochromia golden red (异色瞳)",
    "pointy ears (尖耳朵)",
    "eyes visible through hair (眼透头发)",
    "naughty face (戏弄调戏脸)",
    "cross-eyed (斗鸡眼的)",
    "skin fang (嘴虎牙)",
    "tongue (舌头)",
    "half-closed eyes, (半闭眼)",
    "cheek-to-cheek (脸贴脸)",
    "looking away (不看镜头)",
    "pair of horns (一对角)",
    "forehead (额头)",
    "screaming (尖叫)",
    "teeth (牙齿)",
    "furrowed brow raised eyebrows (八字眉)",
    "Beard (絡腮鬍)",
    "mustache (八字鬍)",
    "confused (困惑)",
    "drunk (酒醉)",
    "colored sclera (有色巩膜（眼白）)",
    "smirk (得意笑)",
    "slit pupils (猫瞳)",
    "pain (疼痛)",
    "round eyes (圆眼)",
    "smile (微笑)",
    "looking at another (看着另一个)",
    "upper teeth (上牙)",
    "blush (脸红)",
    "crying (哭哭)",
    "licking lips (舔嘴唇)",
    "looking up (往上看)",
    "looking to the side (看侧边)",
    "seductive smile (诱人的微笑)",
    "pout (噘嘴)",
    "eyeliner (眼线)",
    "sad (悲伤)",
    "serious (认真)",
    "embarrassed (尴尬害羞)",
    "phoenix eye (丹凤眼)",
    "heterochromia (异色瞳)",
    "eye contact (对视)",
    "headpat (摸头)",
    "singing sang. (唱歌)",
    "beautiful detailed eyes (精细的眼睛)",
    "looking afar (遥望)",
    "annoyed (恼火)",
    "food on face (食物在脸上（by 冬日谎言）)",
    "tongue out (吐舌)",
    "disgust (厌恶)",
    "heterochromia blue red (异色瞳)",
    "cold attitude (冷淡的表情（可能需要与负面词cold搭配使用）)",
    "round teeth (圆齿)",
    "turn pale (脸色苍白)",
    "looking at viewer (看观众)",
    "symbol-shaped pupils (符号瞳)",
    "tears (眼泪)",
    "staring (盯着)",
    "kemomimi (兽耳)",
    "evil smileevil grin (坏笑)",
    "eyeshadow (眼影)",
    "thick eyebrows (浓眉)",
    "looking up,no pupils,empty eyes,drooling,messy_hair,open  mouth, (被催眠的)",
    "v shaped eyebrows (V字眉)",
    "clenched teeth (咬紧牙关)",
    "goatee (山羊鬚)",
    "closed eyes, (闭眼)",
    "wavy mouth (波浪嘴)",
    "breath (呼吸)",
    "facing viewer (面对观众)",
    "upturned eyes (上看的眼睛)",
    "jitome (半开平线眼)",
  ],
  hair: [
    "temple hairs (双侧发)",
    "To reveal the forehead (露额头（没有刘海）)",
    "short hair (短发)",
    "antenna hair (天线毛)",
    "hime_cut (姬发式)",
    "wavy_hair (波浪发型)",
    "cat_ears (猫耳)",
    "sidelocks (耳前发)",
    "half updo (侧发后梳(公主结))",
    "parted bangs (分开浏海)",
    "split-color hair (分色头发)",
    "streaked hair (条纹头发)",
    "side braid (侧织辫)",
    "ponytail (马尾)",
    "quad tails (四马尾)",
    "braided ponytail (编织马尾辫)",
    "pink_hair (粉色头发（羽化前）)",
    "front ponytail (前马尾)",
    "crown braid (冠型织辫)",
    "Medium score (中分)",
    "french braid (法式辫子)",
    "topknot (顶绑发)",
    "two-tone hair (两色头发)",
    "twin braids (双麻花辫)",
    "asymmetrical bangs (不对称浏海)",
    "bareheaded (光头)",
    "black hair (黑色头发（羽化前）)",
    "short twintails (短双马尾)",
    "double_bun (包子头(两个))",
    "blue_hair (蓝色头发)",
    "swept bangs (扫浏海)",
    "brown_hair (棕色头发（羽化前）)",
    "Orange hair (橙色头发)",
    "hair bun (发髻)",
    "hair pulled back (头发后梳)",
    "fox_ears (狐狸耳朵)",
    "blunt_bangs (齐刘海)",
    "medium hair (中长发)",
    "crossed bangs (交叉刘海)",
    "heart hair bun (心型发髻)",
    "blonde hair (金发)",
    "very_long_hair (很长的头发)",
    "braid (麻花辫)",
    "bob cut (鲍伯头)",
    "short_ponytail (短马尾)",
    "hair over one eye (刘海遮单眼)",
    "green_hair (绿发)",
    "uneven twintails (不对称双马尾)",
    "no_nose (没鼻子的)",
    "bow-shaped hair (蝴蝶结发)",
    "low-tied long hair (低扎长发)",
    "twin slut strands (双龙须刘海)",
    "shiny hair (闪亮头发)",
    "rabbit ears (兔子耳朵)",
    "colored inner hair (彩色内毛)",
    "double bun (双发髻)",
    "dreadlocks (脏辫)",
    "cone hair bun (锥形发髻)",
    "flipped hair (翘发)",
    "Waist_length_hair (及腰长发)",
    "blunt bangs (齐浏海)",
    "low twintails (低双马尾)",
    "two side up hair (披肩双马尾)",
    "ringlets (小环管卷发)",
    "straight hair (直发)",
    "loli,white hair,girl,blue eye (白发)",
    "Split head (中分头)",
    "pointy_ears (尖耳)",
    "bowl cut (蘑菇头)",
    "wavy hair (自然卷)",
    "grey_messy_long_hair (灰色杂乱长发)",
    "long wavy curly hair (长长的卷发)",
    "updo hair (团子头(和风))",
    "long hair (长发)",
    "side ponytail (侧马尾)",
    "tongue (舌头)",
    "hair between eyes (眼间发)",
    "green hair (绿发)",
    "braided bun (辫子髻)",
    "purple_hair (紫色头发（羽化前）)",
    "single sidelock (单耳前发)",
    "animal_ears (动物耳朵)",
    "twin_braids (双辫子)",
    "Dynamic hair (动态头发)",
    "twintails (双马尾)",
    "gradient hair (渐变头发)",
    "side_ponytail (侧马尾)",
    "short ponytail (短马尾)",
    "(very long hair),foot length hair,long hair to the ground (长到能拖地的头发(随缘生效))",
    "Pink_brown hair (粉棕色头发)",
    "folded ponytail (折迭马尾辫)",
    "one side up (一侧绑发)",
    "curly_hair (卷发)",
    "two side up (双侧绑发)",
    "short hair with long locks (长耳前+短发)",
    "braided bangs (辫子刘海)",
    "hair flaps (毛瓣)",
    "fangs (尖牙)",
    "slut strands (龙须刘海)",
    "loli red (魅魔萝莉)",
    "drill hair (钻发)",
    "hair intakes (进气口(M毛))",
    "right side temple hair (右边侧发)",
    "one side up hair (披肩单马尾)",
    "saliva (唾液)",
    "single braid (单辫)",
    "wolf ear fluff (狼耳)",
    "hair spread out (头发散落)",
    "single hair bun (单发髻)",
    "colored tips (尖端挑染)",
    "streaked hair (挑染)",
    "long_hair (长发)",
    "very short hair (極短頭髮)",
    "hair_bun (包子头)",
    "Chestnut_hair (栗子色头发)",
    "low twin braids (低双辫)",
    "orange_hair (橙色头发)",
    "doughnut hair bun (甜甜圈发髻)",
    "short_hair (短发)",
    "drill_hair (钻头卷/公主卷)",
    "messy hair (凌乱头发)",
    "floating hair (漂浮的头发)",
    "hair between eyes (两眼之间的头发)",
    "messy_hair (凌乱发型)",
    "twin drills (双钻发)",
    "white hair (白发)",
    "dog_ears (狗耳)",
    "left side temple hair (左边侧发)",
    "curly hair (卷发)",
    "hime cut (姬切)",
    "aqua_hair (水蓝色头发（羽化前）)",
    "multi-tied hair (多绑头发)",
    "multicolored hair (多色头发)",
    "low ponytail (低马尾)",
    "mouse_ears (老鼠耳朵)",
    "pointy hair (尖发动耳发)",
    "ahoge (呆毛)",
    "high ponytail (高马尾)",
    "bob cut (妹妹头)",
    "Underwater portrait (水下，使用于人物，如头发漂浮效果)",
    "bangs (刘海)",
    "payot (长鬓角)",
    "bob (鲍勃头（雷姆式）)",
    "bunny_ears (兔耳)",
    "hair over eyes (刘海遮眼)",
  ],
  pose: {
    safe: [
      "sitting on chair",
      "arms behind back",
      "indian style",
      "gill support",
      "leaning forward",
      "stretching",
      "sitting on the ground",
      "lying",
      "selfie",
      "pray",
      "yoga",
      "salute",
      "floating",
      "sitting",
      "hug self",
      "dynamic pose",
      "lying on back",
      "sitting on bed",
      "kneel",
      "princess carry",
      "walk",
      "standing",
      "on side",
      "hands on hips",
      "arms crossed",
      "hands in hair",
      "knees together",
      "hidden hands",
      "own hands clasped",
      "interlocked fingers",
      "arms up",
      "arms behind head",
      "crossed legs",
      "hugging own legs",
      "double peace hand",
      "arm up",
      "adjusting hair",
      "leg up",
      "clenched hands",
      "tying hair",
      "reaching",
      "arm support",
      "open hands"
    ],
    creative: [
      "w-sitting on the ground",
      "on stomach",
      "huddle, clasp knees",
      "skirt_lift",
      "fighting_stance",
      "wariza",
      "crossed_legs",
      "Skirt lift",
      "sitting on car",
      "squatting",
      "Lie on your side",
      "bent over",
      "half body under water",
      "Put hands around shoulders",
      "pigeon-toed",
      "presenting armpit",
      "outstretched arms",
      "m legs",
      "tail between legs",
      "unbuttoned clothes",
      "skindentation",
      "knees together feet apart",
      "spread toes",
      "feet up",
      "thick_thighs",
      "slim legs",
      "own hands together",
      "spread fingers",
      "cleavage",
      "plantar flexion",
      "sideboob",
      "arms behind back",
      "zombie pose",
      "platform heel",
      "outstretched arm",
      "legs apart",
      "knees to chest",
      "areola_slip",
      "looking over shoulder",
      "collarbone",
      "midriff",
      "hips",
      "bare legs",
      "stretching arms",
      "hands on lap",
      "bare arms",
      "bare shoulders",
      "knees apart",
      "bare back",
      "stretching leg",
      "arms around neck"
    ],
    nsfw: [
      "girl on top",
      "spread legs",
      "thigh gap",
      "arched back",
      "horse riding",
      "clothes_lift",
      "French kiss, proper kiss",
      "all fours",
      "groping",
      "looking through legs",
      "figure four sitting",
      "legs over head",
      "top-down bottom-up",
      "armpits",
      "prostrate, lie flat",
      "missionary position",
      "top-down_bottom-up",
      "trampling",
      "doggystyle",
      "standing split",
      "straddling",
      "girl_on_top,straddling",
      "fetal position",
      "open your legs wide",
      "jack-o' challenge",
      "hand on cortch",
      "puffy areolae",
      "papilla",
      "handjob gesture",
      "tiny tits",
      "ass visible through thighs",
      "hand between legs",
      "between legs",
      "big ass",
      "tiny_chest",
      "NSFW",
      "breast curtains",
      "navel",
      "clothed female nude male",
      "covering mouth",
      "breasts",
      "sitting on person",
      "huge breasts",
      "groin",
      "cameltoe",
      "open clothes",
      "ass",
      "thighs",
      "nipples",
      "areolae",
      "pelvis",
      "hand on own chest",
      "large breasts",
      "medium breasts",
      "small breasts",
      "arms tied",
      "legs tied"
    ]
  },
  clothing: [
    "See-through vest (透明的背心)",
    "Witch dress (魔女风格服)",
    "poncho (小披风)",
    "red shorts (红色短裤)",
    "Cape hood (兜帽斗篷)",
    "apron (围裙)",
    "chinese clothes,china dress, (中国的衣服裙子)",
    "evening dress (晚礼服)",
    "santa (圣诞装)",
    "leggings (紧身裤)",
    "robe (长袍)",
    "school_uniform (学校制服)",
    "soft shell coat (软壳外套)",
    "student training wear (体操服)",
    "red dress (红色连身裙)",
    "pettiskirt (蓬蓬裙)",
    "Light gauze wide sleeve skirt， (轻纱广袖裙)",
    "military_uniform (军装)",
    "gym_uniform (运动制服)",
    "sailor dress (水手裙)",
    "Mai Shiranui (不知火舞)",
    "White clothes (白色衣服)",
    "yukata (浴衣)",
    "Army overcoat (军大衣)",
    "one-piece swimsuit (连体泳衣)",
    "power armor (动力甲)",
    "miniskirt (迷你裙)",
    "Exoskeleton Mecha (外骨骼机甲)",
    "halter dress (绕颈连身裙)",
    "lolita_fashion (洛丽塔风格)",
    "hot underware (情趣内衣)",
    "underwear (内衣)",
    "formal dress (礼服)",
    "Maid dress (A)",
    "black skirt dress, flower pattern in dress,black gown (黑色礼服)",
    "crop top (小可爱露腹短上衣)",
    "lab coat (实验袍)",
    "See-through Pajamas (See-through Pajamas)",
    "dungarees (工装)",
    "hanfu (汉服)",
    "indian clothes,chinese clothes,Cleopatra, (一些风格服饰)",
    "unbuttoned clothes, (武士裤)",
    "sheer tulle dress (薄沙连衣裙)",
    "Belly Dancer (肚皮舞者)",
    "leather jacket (皮衣)",
    "Han Chinese Clothing (汉服)",
    "Red Plaid Shirts (红格衬衫)",
    "latex_bodysuit (乳胶衣)",
    "skirt (裙子)",
    "high-waist pants (高腰裤 （低腰修改为low）)",
    "underpants (内裤)",
    "Rainskirt (雨裙)",
    "highleg leotard (高叉紧身衣)",
    "revealing dress (礼服长裙)",
    "petticoat (衬裙)",
    "cheongsam (旗袍（效果好）)",
    "jumpsuit (连体服（工作服）)",
    "wedding dress (婚纱)",
    "jeans (牛仔裤)",
    "halterdress (绕颈裙)",
    "parka (派克大衣)",
    "trousers with suspenders (吊带裤)",
    "fishnet top (网纹衣)",
    "cow_bikini (奶牛比基尼)",
    "buruma (布鲁玛)",
    "off-shoulder dress (露肩连衣裙)",
    "see-through serafuku (透明水手服)",
    "(((black sundress with round neck,white T-shirt bottom))) (黑色连衣裙+白色打底T恤搭配(请勿去掉tag括号))",
    "sportswear (运动服)",
    "school uniform (校服)",
    "lolita gothic (哥特式洛丽塔)",
    "sweatshirt (圆领卫衣)",
    "shorts (短裤)",
    "no underwear (无内衣)",
    "bathrobe (浴袍)",
    "summer long skirt (夏日长裙)",
    "pocahontas outfit (印第安服饰)",
    "lolita fasion (现代洛丽塔)",
    "chinese clothes+leotard (中式旗袍死库水)",
    "bodysuit (紧身衣)",
    "conjoined black silk (黑丝连体衣)",
    "plaid skirt (短裤)",
    "turtleneck sweater (高领毛衣)",
    "yoga pants (瑜伽裤)",
    "mosaic (拼接款)",
    "latex (乳胶紧身衣(By Yao_men))",
    "office lady suit (OL套装)",
    "kimono (和服)",
    "strapless tank top, navel cutout (抹胸)",
    "sailor dress (水手服)",
    "casual wear (休闲服(素上衣、牛仔裤))",
    "white sailor dress (水手服)",
    "hoodie (连帽衫(带帽卫衣))",
    "raincoat (雨衣)",
    "frillded shirt (荷叶边衬衫)",
    "chiffon dress (雪纺连衣裙)",
    "[Battle Robe:Exoskeleton Mecha:0.3] (机械战甲)",
    "sweater dress (毛衣连身裙)",
    "competition swimsuit (竞赛泳衣)",
    "open-chest sweater (开胸毛衣)",
    "business suit (西装)",
    "Pumpkin skirt (南瓜裙)",
    "heart cutout (心型切口)",
    "taut clothes (紧身衣服)",
    "collared shirt (高领衬衫)",
    "num clothes (修女服)",
    "wedding_dress (1婚纱)",
    "sports bra (运动胸罩)",
    "Greek clothes (希腊服饰)",
    "latex (乳胶衣)",
    "japanese_clothes (和服)",
    "Open-backed sweater (露背毛衣)",
    "Military officer dress (军礼服)",
    "nun gown (修女服)",
    "cheerleading (啦啦隊)",
    "convenience store uniforms (便利店工作服(By 糯米))",
    "leotard (紧身衣)",
    "trousers (西装裤)",
    "Soccer team jersey (足球球衣)",
    "torn clothes (撕裂的衣服)",
    "strapless leotard (无肩带紧身衣)",
    "wearing white sleeveless cheongsam (穿着红色旗袍(颜色可换))",
    "nun clothes (修女服)",
    "gothic_lolita (哥特洛丽塔风格)",
    "navel (露脐)",
    "underboob cutout (下胸切口)",
    "torn clothes (破损的衣物)",
    "nightgown (睡衣)",
    "sweet_lolita (甜美可爱的洛丽塔)",
    "mahou shoujo (马猴烧酒风格)",
    "white_windbreaker (白色风衣)",
    "overcoat (大衣)",
    "less clothes (无)",
    "Cassock (神父/修生黑袍)",
    "slime dress (史莱姆装)",
    "string bikini (系绳比基尼)",
    "[see-through:evening dress:0.3] (透明晚礼服 by czz)",
    "gothic lolita， (哥特萝莉裙)",
    "night dress (睡裙)",
    "Chinese style,One-piece swimsuit，Clothes with gold patterns (中式死库水（辉木）)",
    "summer dress (夏日连衣裙)",
    "front-tie bikini top (前系带比基尼上着)",
    "Black storm jacket (黑色冲锋衣)",
    "waist apron (腰围裙)",
    "highleg swimsuit (高叉泳衣)",
    "hip vent (臀部切口)",
    "strapless dress (无肩带礼服)",
    "sheath dress (包臀裙)",
    "bikini (比基尼)",
    "pajamas (睡衣)",
    "zentai (紧身连体衣)",
    "micro bikini (迷你比基尼)",
    "Standing collar long windbreaker (长袖运动服（直译为立领长风衣）)",
    "black pleated skirt (黑百褶裙)",
    "V-NECK SWEATER VEST (V领针织毛衣（无袖背心）)",
    "conjoined white silk (连体白丝)",
    "trench_coat (战壕风衣)",
    "Long skirt (长裙)",
    "wet clothes (湿润的衣服)",
    "leotards (紧身连衣裤)",
    "reverse bunny suit (逆兔女郎)",
    "serafuku (水手服)",
    "thong (丁字裤)",
    "Bunny Girl (兔女郎)",
    "pleated skirt (半身百褶裙)",
    "racing suit (赛车服(By KimZuo))",
    "Denim suspenders (吊带牛仔裤)",
    "corset (束腹)",
    "volleyball uniform (排球服)",
    "loli,one girl,domineering lady, nun (修女)",
    "white skirt (白色连衣裙)",
    "cropped shoulders (露肩)",
    "blue and white striped bikini (蓝白条纹比基尼)",
    "bra visible through clothes (透过衣服能看到胸罩)",
    "sweater (毛衣)",
    "serafuku, (萝莉)",
    "Battle Robe (战袍)",
    "sweet_lolita (sweet_lolita,)",
    "tank top (背心)",
    "japanese yukata (日式浴衣)",
    "black skirt dress, flower pattern in dress,black gow (花卉图案连衣裙（黑）)",
    "one-piece dress (连衣裙)",
    "leotard under clothes (衣服下紧身衣)",
    "armor (铠甲)",
    "Miko clothing (巫女服)",
    "jumper skirt (背心裙)",
    "neck ribbon (頸帶)",
    "Taoist robe (道袍)",
    "lace-trimmed bra (蕾丝边胸罩)",
    "tan line (曬痕)",
    "nurse (护士服(By Yao_men))",
    "suspender skirt (吊带裙)",
    "Raincoat (雨衣)",
    "frock (罩衫)",
    "backless dress (露背连身裙)",
    "white skirt dress, flower pattern in dress,white gow (花卉图案连衣裙（白）)",
    "nontraditional miko (改造巫女服)",
    "pants (裤子)",
    "untied bikini (解开比基尼)",
    "lab_coat (白大褂(By Yao_men))",
    "thong leotard (丁字紧身衣)",
    "black suit (西服(black黑)-by bilibili-跑酷)",
    "bulletproof_vest, (防弹衣)",
    "white shirt (白衬衫)",
    "taut shirt (紧身衬衫)",
    "side-tie bikini bottom (侧系带比基尼下着)",
    "school swimsuit (学校泳衣)",
    "back cutout (后背切口)",
    "layered skirt (【补档】分层群)",
    "soaked (浸湿（如果有内衣会透的更明显）)",
    "full dress (礼服)",
    "dress (连身裙)",
    "combat suit (战斗服)",
    "exoskeleton (外骨骼)",
    "coat (外套)",
    "Maid dress (女仆装)",
    "slingshot swimsuit (高叉泳衣)",
    "cloak (披风)",
    "swimsuit (泳装)",
    "china dress (旗袍)",
    "shoulder cutout (肩膀切口)",
    "pencil skirt (铅笔裙)",
    "revealing clothes (暴露的衣服)",
    "sleeveless shirt (无袖衬衫)",
    "denim shorts (牛仔短裤)",
    "no_bra (无胸罩)",
    "Organza lace (透明硬纱/蕾丝花边)",
    "ribbed sweater (罗纹毛衣)",
    "spider web print (蛛网纹路)",
    "street wear (街头风格服饰)",
    "Space suit (宇航服（配合科幻标签）)",
    "backless outfit (露背装)",
    "Dirndl (紧身连衣裙)",
    "microskirt (微型短裙)",
    "armored dress (盔甲裙)",
    "cameltoe (骆驼趾/骆驼肌(紧身效果))",
    "low-waist pants (低腰裤 （高腰修改为high）)",
    "hospital gown (病号服)",
    "wind coat (风衣)",
    "wind coat,skirt,scarf, gloves, leg belt, arm strap, hairclip, (方舟风格服装（2019刻板印象）)",
    "pleated dress (带褶连衣裙)",
    "off-shoulder sweater (露肩毛衣)",
    "mechanical clothes (机械服装)",
    "fundoshi (兜裆布)",
    "bloomers (灯笼裤)",
    "see-through (透明衣服)",
    "military uniform (军装)",
    "halloween_costume (万圣节服装)",
  ],
  accessories: [
    "bodystocking (连身袜)",
    "FLIGHT Goggles (飛行員護目鏡)",
    "gagged (口球)",
    "shibari (束缚)",
    "head chain, jewelry (头链 (参考Wlop风铃公主的头饰，成功率低))",
    "wings (翅膀)",
    "cabbie_hat (报童帽)",
    "white pantyhose (白裤袜)",
    "geta (木屐)",
    "firearms (枪械)",
    "shackles (脚铐)",
    "white ankle socks (白色短袜)",
    "stirrup legwear (踩脚袜，马镫裤)",
    "rabbit tail (兔尾)",
    "jack-o'-lantern (捷克南瓜燈)",
    "glaive (阔剑/弯刀/飞刀)",
    "striped_thighhighs (条纹过膝袜)",
    "loli (黑丝)",
    "earmuffs (御寒耳罩)",
    "kneehighs (长袜(By 好人))",
    "sneakers (运动鞋)",
    "bell collar (铃铛项圈)",
    "elbow gloves (肘部手套)",
    "high heels (高跟鞋)",
    "red flag (红旗)",
    "baseball_cap (棒球帽)",
    "Rainboots (雨靴)",
    "thighband pantyhose (绑腿连裤袜)",
    "antenna hair clips (天线头饰（类似于碧蓝航线中绫波的头饰）)",
    "ankle boots (短靴)",
    "pantyhose (裤袜)",
    "hair stick (发簪)",
    "wizard hat (巫师帽)",
    "laptop (笔记本电脑)",
    "fine fabric emphasis (精细面料/有质感的(丝袜))",
    "hair ribbon (发带)",
    "Sun hat with wavy brim (波浪帽檐遮阳帽)",
    "bowtie (领结)",
    "ribbon (丝带)",
    "batwing (蝙蝠翅膀)",
    "High heeled gift shoes (高跟礼鞋)",
    "garter (腿环)",
    "collar (项圈)",
    "hair rings (发环)",
    "bat_wing (蝙蝠翅膀)",
    "cane (手杖)",
    "sleeves (袖子)",
    "bangle (手镯)",
    "latex glove (乳胶手套)",
    "magic stck (魔法棒)",
    "elbow_gloves (长袖手套)",
    "thigh boots (过膝长靴)",
    "headphone (耳机)",
    "hair_flower (发花)",
    "knee boots (膝下靴)",
    "no shoes (不穿鞋)",
    "Guitar (吉它)",
    "hood (兜帽)",
    "beret (贝雷帽)",
    "uwabaki (女式学生鞋)",
    "wedge heels (坡跟鞋)",
    "wrist cuffs (手腕袖口)",
    "Samurai Sword (武士刀)",
    "thigh strap (大腿带)",
    "zun hat (zun帽)",
    "tabi (日本式短布袜)",
    "Baseball cap (棒球帽)",
    "short sleeves (短袖)",
    "pink_thighhighs (粉色过膝袜(By 好人))",
    "Badge, Mountain, River, Colorful (胸牌)",
    "stiletto heels (细高跟)",
    "detached sleeves (分离式袖子)",
    "belt (腰带)",
    "garter straps garter belt (吊袜带)",
    "mittens (连指手套)",
    "lace-trimmed_gloves (蕾丝边手套)",
    "lace-up boots (系带靴)",
    "Knitted hat (针织帽)",
    "open toe high (露趾高跟鞋)",
    "white_thighhighs (白色过膝袜)",
    "bell (铃铛)",
    "socks (袜子)",
    "necklace (项链)",
    "cowbell (牛铃)",
    "musical_notes (音符/五线谱)",
    "butterfly (蝴蝶)",
    "Holding the wedding bouquet with both hands (手捧花（花嫁）)",
    "loafers (乐福鞋)",
    "wide sleeves (宽袖)",
    "nurse cap (护士帽)",
    "bridal gauntlets (婚礼手套)",
    "capelet (披肩)",
    "platform boots (厚底高跟靴)",
    "toeless legwear (无趾护腿)",
    "strappy heels (有带子的高跟鞋)",
    "earrings (耳环)",
    "monocular glasses (单片眼镜)",
    "sandals (凉鞋)",
    "Ushanka (苏联毛帽)",
    "pointe shoes (芭蕾舞足尖鞋)",
    "white stocking, (white stocking,)",
    "combat boots (战术靴)",
    "black stocking (黑丝(By 你不史蒂夫))",
    "pocket watch pendant (怀表)",
    "floral headwear (鲜花头饰)",
    "giant green shark tail (粗尾巴)",
    "scarf (围巾)",
    "tiaras (抹额（公主冠）（by残阳）)",
    "high heeled sandals (高跟凉鞋)",
    "sunglasses (太阳镜)",
    "christmas hat (圣诞帽)",
    "seamed legwear (接缝裤袜)",
    "bracelet (手镯)",
    "barefoot (赤脚)",
    "suspenders (吊带)",
    "maid headdress (女仆头饰)",
    "backpack (背包)",
    "flower_crown (花环)",
    "green_thighhighs (绿色过膝)",
    "naval cap (海军帽)",
    "armlet (臂环/臂章)",
    "book (书)",
    "lace-trimmed (蕾丝的，后面加东西就行)",
    "fishnet pantyhose (网裤袜)",
    "blindfold (眼罩)",
    "sailor collar (水手领)",
    "hair_bow (蝴蝶结发饰)",
    "bandage (绷带)",
    "casqueete (鸭舌帽)",
    "thighhighs_on_one_leg (过膝袜（单侧）)",
    "bridal veil (婚礼面纱)",
    "mary_janes (玛丽珍鞋（猪腰子鞋）)",
    "Tactical bulletproof vest (防弹背心)",
    "Flip-flops (人字拖)",
    "pantyhose pull (拉下裤袜)",
    "loose_socks (泡泡袜(By 好人))",
    "hair bow (蝴蝶结)",
    "tail (尾巴)",
    "wolf ears (狼耳)",
    "tassel (流苏)",
    "high helled low knee boots (高跟膝下靴)",
    "crown (皇冠)",
    "mouth mask (口罩)",
    "medal (勋章)",
    "Wings with sun gears (太阳齿轮翅膀(大量齿轮,翅膀更多更乱,效果意外不错)",
    "wand,magic, (法杖)",
    "A rock with runes (符文宝石)",
    "thighhighs (过膝袜)",
    "wire (电线)",
    "gem (宝石)",
    "(miko thighhighs) (巫女袜)",
    "mask (面罩)",
    "tie (领带)",
    "capelet (斗篷)",
    "hairclip (发夹)",
    "cross-laced footwear (交叉系带鞋)",
    "hair ornament (发饰)",
    "black pantyhose (黑色裤袜)",
    "peaked cap (鸭舌帽)",
    "puffy sleeves (蓬松的大袖子)",
    "headband (额前的发带)",
    "veil (头纱)",
    "kneehighs (膝下袜)",
    "long gloves (长手套)",
    "gloves (手套)",
    "fox mask (狐狸面具)",
    "leather shoes (皮鞋)",
    "crotchless pantyhose (无裤裆丝袜)",
    "Long sleeve (长袖)",
    "white stocking (白丝(By 你不史蒂夫))",
    "fisherman's hat (漁夫帽)",
    "paw gloves (猫猫手套)",
    "laxet glove (乳胶手套)",
    "hair flower (发花)",
    "cross necklace (十字架项链)",
    "tail insertion (尾巴插入（臀部出现尾巴）)",
    "boots (靴子)",
    "garter_belt (连腰吊带袜(By 好人))",
    "High heeled boots (高跟长筒靴)",
    "glasses (眼镜)",
    "fingerless gloves (无指手套)",
    "(magic hat) (魔法帽)",
    "leg ring (腿环)",
    "hairband (发卡)",
    "latex gloves (乳胶手套)",
    "Tactical gloves (战术手套)",
    "choker (贴颈项链)",
    "slippers (拖鞋)",
    "buttons (纽扣)",
    "halo (光环)",
    "tiara (三重冕)",
    "necktie (领带)",
    "neck ribbon (颈带)",
    "veil mouth veil (薄纱面纱)",
    "eyepatch (眼罩(独眼))",
    "Christmas Hat (圣诞帽)",
    "no shoe (不穿鞋)",
    "sleeveless (无袖)",
    "The wheel of fire (火焰之轮（附着火焰的法轮？）)",
    "navel piercing (脐钉)",
    "shells on the bench,stones on the bench (海滩上的石头，贝壳)",
    "lact-trimmed (蕾丝的，后面加东西就行)",
    "High heeled evening shoes (高跟礼鞋)",
    "striped_socks (横条袜(By 好人))",
    "legwear (裹腿(一般为丝袜))",
    "Witch_hat (女巫帽)",
    "Oilpaper umbrella (油纸伞)",
    "ahoge (呆毛)",
    "hat ribbon (帽带)",
    "pockets (口袋)",
    "censored choker (审查的项链)",
    "handcuffs (手铐)",
    "straw hat (草帽)",
    "boxing gloves (拳击手套)",
    "broom (扫把)",
    "black_thighhighs (黑色过膝袜)",
    "red_scarf (红围巾)",
    "gauntlets, (金属手套)",
    "ribbon-trimmed_legwear (边缘系带的日式袜子)",
    "Cold-weather mask (口罩)",
    "umbrella (伞)",
    "with lightsaber (光剑)",
    "ribbon-trimmed sleeves (丝带饰边袖子)",
  ],
  environment: [
    "gohei (神社)",
    "red Soviet (苏联红军)",
    "symmetrical (对称)",
    "christmas tree (圣诞树)",
    "cropped shoulders (肩下剪裁)",
    "shanty town/slum (贫民窟)",
    "detailed background (详细背景)",
    "building architecture (建筑物)",
    "battlefield (战场)",
    "Bustling city (繁华都市)",
    "dakimakura (抱枕)",
    "field (田园)",
    "treehouse (树屋)",
    "bathroom (浴室)",
    "cropped torso upper body (躯干下剪裁)",
    "lawn (草坪)",
    "floating white feathers (漂浮的白色羽毛)",
    "desk gothic (哥特式桌子)",
    "firework (烟花)",
    "river (河流)",
    "raindrop (雨滴（效果极好）)",
    "Simple pattern background (简单花纹背景)",
    "torii (鸟居)",
    "outdoors (室外)",
    "kitchen (厨房)",
    "building_ruins (建筑废墟)",
    "amusement park,advertise,poster (游乐园海报)",
    "coffee house (咖啡馆)",
    "gear (齿轮)",
    "fountain (喷泉)",
    "out of frame (人物超出框)",
    "restaurant (饭店)",
    "museum (博物馆)",
    "modern,Europe (法兰西)",
    "alpine (高山，山脉)",
    "on bed (在床上)",
    "shop (商店)",
    "bedroom (卧室)",
    "drop shadow (投影阴影)",
    "temple (寺庙)",
    "red moon (红月，血月)",
    "road (道路)",
    "pleated skirt,heterochromia, ukiyo-e,poncho, (萌萌)",
    "ray tracing (光线追踪)",
    "blur_background (背景虚化)",
    "art room (美术室)",
    "starry sky,clusters of stars (繁星)",
    "grassland (草地)",
    "zoom layer (缩放投影图层)",
    "sea (海水)",
    "skyscraper (摩天楼)",
    "server room (服务器机房)",
    "crescent (新月)",
    "cropped arms (手臂下剪裁)",
    "China Jiangnan water town style (中国江南水乡风格)",
    "floating sakura (散落樱花)",
    "library (图书馆)",
    "farm (农场)",
    "beach background (沙滩背景)",
    "violet (紫罗兰)",
    "tatami (塌塌米)",
    "outline (轮廓线)",
    "ruins (废墟)",
    "beach (海边)",
    "laboratory (实验室)",
    "close-up (特写)",
    "Dreamy forest (梦幻之森(虚幻感.光粒子幽静))",
    "rain (雨)",
    "blurry background (模糊背景)",
    "classroom (教室)",
    "gothic architecture (哥特式建筑)",
    "shooting star (流星)",
    "warehouse (仓库)",
    "colorful startrails (五彩斑斓的星轨)",
    "lovely (学校)",
    "space (太空)",
    "space background (空间背景)",
    "firefly (萤火虫)",
    "expressions (表情表)",
    "beige background (米色背景)",
    "Ally ahijah  Powder coat  The blue eye (Ally ahijah)",
    "backlighting (背光)",
    "snowflakes (雪花)",
    "stained glass (（教堂的）彩绘玻璃)",
    "electricity (电流)",
    "street (街道)",
    "cityscape (城市背景)",
    "cut-in (插入画面)",
    "cyberpunk, city, kowloon, rain (赛博朋克)",
    "onsen (温泉)",
    "no humans (无人)",
    "sunlight on the desk ,8K ,high definition, 8K, real--test--creative (d)",
    "gradient background (渐变背景)",
    "snowfield (雪地)",
    "engine room (轮机舱)",
    "starry sky,clusters of stars,starry sky,glinting stars, (星空)",
    "petals floating in the wind (飘散的花瓣)",
    "dormitory (宿舍)",
    "cowboy shot (牛仔特写)",
    "portrait (人像)",
    "flying butterfly (飞翔的蝴蝶)",
    "incredibly_absurdres (超高分辨率出图)",
    "French window (落地窗)",
    "snow (雪 by czz)",
    "flowers meadows (繁花草甸)",
    "clockbackground (时钟背景)",
    "cropped legs (腿下剪裁)",
    "simple background (简单背景)",
    "Racing Track (赛车场)",
    "selfiemirror (自拍)",
    "feet out of frame (足超出框)",
    "ocean (海洋)",
    "upper body (上半身)",
    "nature (大自然)",
    "airport background (机场背景)",
    "loli girl moon night light lake glass (月夜)",
    "cyberpunk city (赛博朋克城市)",
    "silhouette (剪影)",
    "dungeon background (地牢背景)",
    "neon lights (霓虹灯)",
    "white background (白色背景)",
    "cafe (咖啡馆)",
    "gym (健身房)",
    "aurora (极光)",
    "basement (地下室)",
    "prison (监狱)",
    "sunburst background (旭日纹背景)",
    "forest (森林)",
    "chinese style architecture (古风建筑)",
    "mountain (山脉)",
    "starry sky (星空)",
    "full body (全身)",
    "greco-roman architecture (西罗马建筑)",
    "Fireworks (烟花)",
    "cityscape (城市风景)",
    "indoors (室内)",
    "handrail (栏杆)",
    "Cherry blossoms (櫻花)",
    "blue sky with clouds (蓝天白云)",
    "lower body (下半身)",
    "electrical room (配电房)",
    "east asian architecture (东亚建物)",
    "Alps (阿尔卑斯山脉)",
    "street lamp (路灯)",
    "church (教堂)",
    "Industrial wind, Chinese architecture (工业化古建筑)",
    "gilt border (镀金边框)",
    "stairs (楼梯)",
    "glinting stars (闪烁的星星)",
    "bokeh (散景)",
    "clock_background (时钟背景)",
    "bathing (浴室)",
    "head out of frame (头超出框)",
    "Blue hair girl T-shirt short pants long hair no glasses (Test)",
    "Isekai cityscape (異世界奇幻城市)",
    "lake (湖泊)",
  ],
  style: [
    "intense angle (强烈镜头)",
    "Cyberpunk (赛博朋克)",
    "lens 135mm,f1.8 (聚焦人物镜头)",
    "1990s (style) (1990风格)",
    "fate stay night; saber (fate stay night; saber)",
    "backlight (背光)",
    "dutch angle (斜角镜头)",
    "pixel art (像素风)",
    "dakimakura (抱枕)",
    "beautiful detailed water (漂亮的水)",
    "hip focus (臀部焦点)",
    "picture frame (边框)",
    "beautiful detailed sky (漂亮的天空)",
    "multiple views (多视图)",
    "pov crotch (胯部主观视角)",
    "from side (侧边视角)",
    "tarot (塔罗牌风格)",
    "megami magazine (女神杂志)",
    "papercraft (纸模)",
    "Yu-Gi-Oh,kazuki takahashi (游戏王)",
    "female focus (女性焦点)",
    "photorealistic (逼真的)",
    "character design (角色设定图)",
    "realistic (写实)",
    "god rays (自上而下的光)",
    "chromatic aberration (色差(类似于抖音的logo那种))",
    "ultrawide shot (超广角)",
    "Ink wash painting (水墨)",
    "voxel art (体素画)",
    "chibi (Q版)",
    "ink splashing (墨水溅)",
    "facing away (人物面朝远方(背对))",
    "foreshortening (正前缩距)",
    "Unity Creations (统一风格)",
    "intricate detail (复杂的细节)",
    "fake screenshot (伪截图)",
    "profile (侧脸)",
    "comic (漫画)",
    "ray tracing (光线追踪)",
    "pov hands (手主观视角)",
    "monochrome (单色画)",
    "official art (官方图)",
    "monochrome (单色)",
    "sketch (素描)",
    "art of light novel (轻小说插画风)",
    "sunlight (阳光)",
    "male focus (男性焦点)",
    "back focus (背后焦点)",
    "greyscale (灰度)",
    "dramatic angle (戏剧性镜头)",
    "4koma (四格漫画)",
    "Aestheticism Painting (唯美主义)",
    "three sided view (三视图)",
    "colored pencil drawing (彩铅绘)",
    "partially colored (部分着色)",
    "Loong, dragon background, loong background (龙背景)",
    "flat shading (平面着色)",
    "anime screencap (动漫截图)",
    "dynamic angle (动态镜头)",
    "soviet poster (苏维埃海报)",
    "straight-on (正面面对)",
    "high contrast (高对比度度)",
    "{{{origami art}}}, paper art (折纸艺术)",
    "flat color (纯色块)",
    "from below (低位视角)",
    "Conceptual art of futuristic yin-yang swordsmen, (未来+阴阳 概念)",
    "pixel art (像素画)",
    "highres (高分辨率)",
    "from behind (背后视角)",
    "tachie (立绘)",
    "Precise geometry (精确的几何形状)",
    "wide shot (远景)",
    "vector tracing (矢量追踪)",
    "screentones (网点)",
    "chromatic aberration (色差色失焦)",
    "magazine scan (杂志扫图)",
    "Tenebrism, (暗色调)",
    "Valentine (情人节沙发)",
    "ukiyo-e (浮世繪)",
    "Line art (线稿)",
    "flat color (平涂/平色)",
    "Steampunk (蒸汽朋克风)",
    "{rough sketch} (草稿风)",
    "from the Side below (侧下)",
    "from above (高位视角)",
    "magazine cover (杂志封面)",
    "ukiyo-e (浮世绘)",
    "masterpiece (提取高质量数据)",
    "{{splatoon}} (斯普拉遁)",
    "90's (90年代)",
    "rough sketch (素描草图)",
    "foot focus (足部焦点)",
    "reference sheet (三视图进阶)",
    "pixiv id (p站风格)",
    "cyberpunk (赛博朋克)",
    "poster (海报)",
    "Vaporwave (蒸汽波)",
    "figure (手办)",
    "octane render (OC渲染器)",
    "official art (三视图进阶)",
    "watercolor (水彩画)",
    "glowing light (荧光)",
    "colorful (色彩化)",
    "perspective (透视)",
    "overall view, (全景)",
    "traditional media (传统媒体)",
    "high saturation (高饱和度)",
    "lens flare (镜头光晕)",
    "cinematic angle (电影角度)",
    "artbook (原画)",
    "concept art (三视图进阶)",
    "1980s (style) (1980风格)",
    "illustration (插图)",
    "realistic (现实的)",
    "science fiction (科幻风格)",
    "Ink anime (水墨动漫风)",
    "minimalist-lines (极简线条)",
    "retro artstyle (复古风格)",
    "game cg (CG)",
    "motion blur (运动模糊)",
    "official art, red background, flat color, partially colored, {persona 5} (Persona 5 风格)",
    "silhouette (剪影)",
    "sharp focus (锐聚焦)",
    "doujinshi doujin cover (同人志风)",
    "ink and wash painting (水墨画)",
    "extremely detailed CG unity 8k wallpaper (高清壁纸)",
    "cinematic angle (电影镜头)",
    "comic book (漫画书)",
    "detailed manga illustration (精细漫画插画)",
    "reflection light (反射光)",
    "pov (主观视角)",
    "art nouveau (新艺术运动(慕夏))",
    "Clear picture (清晰的图片)",
    "capanime screencap (动画截图)",
    "grayscale (灰度图)",
    "flat color (平涂)",
    "card games (卡牌风)",
    "depth of field (景深)",
    "{{{paper Figure}}}, origami art, 3d (纸艺风格)",
    "upside-down (颠倒)",
    "ass focus (pp焦点)",
    "gold trim (金边修饰效果)",
    "outline (描边)",
    "blurry background (多人背景)",
    "first-person view (第一人称)",
    "cinematiclighting (电影光效)",
    "masterpiece (杰作)",
    "looking at viewer,(from side:1.2),( head tilt:1.65),(leaning_back:1.25) (新房45度(By 姓符的绅士))",
    "contour deepening (轮廓加深)",
    "depthoffield (景深)",
    "fisheye (鱼眼)",
    "from the Side below Black silk (侧下)",
    "line art (线条艺术)",
  ],
  nsfw: [
    "nsfw, extremely explicit",
    "completely nude",
    "uncensored",
    "topless, bottomless",
    "detailed nipples, detailed pussy",
    "extreme cleavage, spreading legs",
    "ahegao, drooling, cross-eyed",
    "sweat drops on body, body fluids, shiny skin",
    "bondage, shibari, tied up",
    "transparent clothing, see-through latex, wet shirt",
    "micro bikini, strings, pasties",
    "leash and collar, submissive pose",
    "breast grab, thigh grab",
    "cameltoe, camel toe",
    "nipple slip, panty pull",
    "squatting, all fours, doggy pose",
    "intense physical contact, groping",
    "tearing clothes, ripped clothes",
    "sensual biting, tongue out",
    "hypnotized eyes, empty eyes, mind break",
    "succubus wings, succubus tail, succubus outfit",
    "tentacles, monster girl elements",
    "glory hole, gloryhole (implied)",
    "breast pressing against glass/wall",
    "milk dripping, sticky liquids on skin",
    "chocolate body paint, whipped cream covering",
    "vibrator (implied), toys (implied)"
  ]
};

export const getRandomTags = (category: keyof typeof tagLibrary, count: number, securityLevel: 'safe' | 'creative' | 'nsfw' = 'safe'): string => {
  const lib = tagLibrary[category];
  
  let sourceArray: string[] = [];
  
  if (Array.isArray(lib)) {
    sourceArray = lib;
  } else if (typeof lib === 'object' && lib !== null && !Array.isArray(lib)) {
    // 处理分级的 pose 类别
    if (securityLevel === 'safe') {
      sourceArray = lib.safe || [];
    } else if (securityLevel === 'creative') {
      sourceArray = [...(lib.safe || []), ...(lib.creative || [])];
    } else {
      sourceArray = [...(lib.safe || []), ...(lib.creative || []), ...(lib.nsfw || [])];
    }
  }

  if (!sourceArray || sourceArray.length === 0) return "";
  
  const shuffled = [...sourceArray].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count).join(", ");
};
